void exception() {
  try {
    throw "error message";
  } catch (const char *e) {}
}
